config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reservations, except: [:destroy]
  resources :reviews, only: [:show, :new, :create]
  resources :homes
  resources :pets
  resources :users, only: [:show] do
    collection do 
      get :profile
    end
  end

  get '/homes/:id/reviews' => 'reviews#index', as: 'homes_reviews'
  get '/homes/:id/delete' => 'homes#destroy', as: 'homes_delete'
  get '/pets/:id/delete' => 'pets#destroy', as: 'pets_delete'
  get 'users/index'
  post 'notifications/:id/mark_as_read' => 'notifications#mark_as_read'
  post 'notifications/mark_as_read' => 'notifications#mark_as_read'


  root 'pages#home'

  match '/users',   to: 'users#index', via: 'get'
  put '/users/:id', action: :verify, controller: 'users'
  post '/search_homes' => 'homes#search'
  get '/search_homes' => 'homes#index'
  get '/my_homes' => 'homes#my_homes', as: 'my_homes'

  get '/homes/search_homes', action: :index, controller: 'homes'

  post '/reservations/new', to: 'reservations#new'
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  validates :name, :breed, :description, presence: true
  validate :validate_photo 
  
  private 
  def validate_photo 
    unless photo and photo.content_type =~ /^image\/(jpeg|pjpeg|gif|png|bmp)$/ 
      errors.add(:photo, "Not a valid image") 
    end 
  end 
end

app/controllers/pets_controller.rb
# frozen_string_literal: true

class PetsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /pets or /pets.json
  def index
    @pets = Pet.all.where(user_id: current_user)
  end

  # GET /pets/1 or /pets/1.json
  def show; end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit; end

  # POST /pets or /pets.json
  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user

    respond_to do |format|
      if @pet.save
        format.html { redirect_to pet_url(@pet), notice: 'Su mascota fue registrada correctamente' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1 or /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to pet_url(@pet), notice: 'Los datos de su mascota se actualizaron correctamente' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1 or /pets/1.json
  def destroy
    @pet.destroy

    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'El registro de su mascota fue eliminado correctamente' }
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def pet_params
    params.require(:pet).permit(:name, :breed, :description, :user_id, :photo)
  end
end

app/views/pets/_form.html.erb
<div class="new-model">
  <%= form_with(model: pet) do |form| %>
    <% if pet.errors.any? %>
      <div class="invalid-form">
        <p>Ha ocurrido un error:</p>
        <aside>
          <% pet.errors.each do |error| %>
            <p><%= error.full_message %></p>
          <% end %>
        </aside>
      </div>
    <% end %>
    <div class="edit-sect-1">
      <% if action_name == 'edit' %>
        <div class="file-field">
          <%= form.label :photo do %>
            <span><strong>Actualizar foto:</strong></span>
            <div class="upload photo upload-edit">
              <%= form.file_field :photo, onchange: 'loadFile(event)', class: 'input-file'%>
              <% if pet.photo.attached? %>
                <span id="add" hidden >+</span>
                <%= image_tag(pet.photo, id: 'output')  %>
              <% else %>
                <img id="output"/>
              <% end %>
              <div class="trash-icon"></div>
            </div>
          <% end %>
        </div>
      <% else %>
        <div class="file-field">
          <%= form.label :photo do %>
            <span><strong>Subir foto:</strong></span>
            <div class="upload photo">
              <%= form.file_field :photo, onchange: 'loadFile(event)', class: 'input-file', required: true %>
              <span id="add">+</span>
              <img id="output"/>
              <div class="trash-icon"></div>
            </div>
          <% end %>
        </div>
      <% end %>
      <aside class="new-home-form pets">
        <% if action_name == 'new' %>
          <h1>Registra a tu mascota</h1>
        <% else %>
          <h1>Actualiza la información de tu mascota</h1>
        <% end %>
        <div class="field">
          <%= form.label :name, 'Nombre', style: "display: block" %>
          <%= form.text_field :name, placeholder: 'Nombre de tu mascota' %>
        </div>
        <div class="field">
          <%= form.label :breed, 'Raza', style: "display: block" %>
          <%= form.text_field :breed, placeholder: 'Raza de tu mascota' %>
        </div>
      </aside>
    </div>
    <div class="field">
      <%= form.label :description, 'Descripción', style: "display: block" %>
      <%= form.text_area :description, placeholder: 'Breve descripción' %>
    </div>
    <div class="button-back">
      <div class="actions">
        <%= form.submit 'Guardar', class: "button" %>
      </div>
    </div>
  <% end %>
</div>
<div id="icon-back links">
  <a href= <%= pets_path %>><i class="fa-solid fa-arrow-rotate-left"></i></a>
</div>

app/views/pets/_pet.html.erb
<div id="<%= dom_id pet %>" class="pet-id">
  <div class="new-desktop pets-view">
    <div class="content-pet">
      <div class="new-pet-photo">
        <p class="img-photo">
          <%= image_tag pet.photo.variant(resize_to_limit: [300, 300]), class:"img-main" %>
        </p>
      </div>  
      <div class="field-pet-photo">
        <p>
        <strong>Nombre:</strong>
          <%= pet.name %>
        </p>
        <p>
          <strong>Raza:</strong>
          <%= pet.breed %>
        </p>
        <p>
          <strong>Descripción:</strong>
          <%= pet.description %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/pets/edit.html.erb
<%= render "form", pet: @pet %>

app/views/pets/index.html.erb
<h1>Tus mascotas</h1>
<div id="pets">
  <% @pets.each do |pet| %>
      <%= link_to pet do %>
        <%= render pet %>
      <% end %>
  <% end %>
  <%= link_to new_pet_path, class: 'home-card add-model pets-view' do %>
    <span>+</span>
  <% end %>
</div>

app/views/pets/new.html.erb
<%= render "form", pet: @pet %>

app/views/pets/show.html.erb
<%= render @pet %>
<div class="show-pets-buttons links">
  <a href= <%= edit_pet_path(@pet) %>><i class="fa-solid fa-pen-to-square"></i></a>
  <a href= <%= pets_path %>><i class="fa-solid fa-arrow-rotate-left"></i></a>
  <%= link_to '<i class="fa-solid fa-trash-can"></i>'.html_safe, pets_delete_path(@pet) %>
</div>   