config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reservations, except: [:destroy]
  resources :reviews, only: [:show, :new, :create]
  resources :homes
  resources :pets
  resources :users, only: [:show] do
    collection do 
      get :profile
    end
  end

  get '/homes/:id/reviews' => 'reviews#index', as: 'homes_reviews'
  get '/homes/:id/delete' => 'homes#destroy', as: 'homes_delete'
  get '/pets/:id/delete' => 'pets#destroy', as: 'pets_delete'
  get 'users/index'
  post 'notifications/:id/mark_as_read' => 'notifications#mark_as_read'
  post 'notifications/mark_as_read' => 'notifications#mark_as_read'


  root 'pages#home'

  match '/users',   to: 'users#index', via: 'get'
  put '/users/:id', action: :verify, controller: 'users'
  post '/search_homes' => 'homes#search'
  get '/search_homes' => 'homes#index'
  get '/my_homes' => 'homes#my_homes', as: 'my_homes'

  get '/homes/search_homes', action: :index, controller: 'homes'

  post '/reservations/new', to: 'reservations#new'
end

app/views/partials/_calendar.html.erb
<div class="reservation-calendar">
  <%= month_calendar(events: meetings) do |date, meetings| %>
    <%= date.day %>
  <% end %>
</div>

app/views/partials/_footer.html.erb
<footer>
  <div class="footer-info">
  
  <figure>
    <%= image_tag "logo-bc.png", class:"image"%>
  </figure>

    <div class="info">
      <div class="contact">
        <div class="contact-info">
          <p>
            ¡Cuidando perros desde el renacentismo pa!
          </p>
        </div>
  
        <div class="contact-info">
          <i class="fa-solid fa-mobile-screen"></i>
          <p>+52-312-777-6969</p>
        </div>
  
        <div class="contact-info">
          <i class="fa-solid fa-envelope"></i>
          <p>petcare@gmail.com</p>
        </div>
      </div>

      <div class="list">
        <ul>
          <li>Acerca de nosotros</li>
          <li>¿Qué hacemos?</li>
          <li>FAQ</li>
          <li>Contáctanos</li>
        </ul>
      </div>

      <div class="social">
        <div>
          <a href="https://es-la.facebook.com/"  target="_blank">
            <i class="fab fa-facebook-f"></i>
          </a>
        </div>
        <div>
          <a href="https://twitter.com/" target="_blank">
            <i class="fa-brands fa-twitter"></i>
          </a>
        </div>
        <div>
          <a href="https://www.instagram.com/" target="_blank">
            <i class="fab fa-instagram"></i>
          </a>
        </div>
      </div>
    </div>

    <span>© Copyright 2022 Petcare. All rights reserved.</span>
  </div>
</footer>

app/views/partials/_general_options.html.erb
<aside class="general-menu menu" id="general-menu">
  <h1>Mejora tu busqueda</h1>
  <section class="options-menu">
    <li><%= link_to 'Más recientes', homes_path(filter: 'date') %></li>
    <li><%= link_to 'Mejor reputación', homes_path(filter: 'score') %></li>
    <li><%= link_to 'Menor costo', homes_path(filter: 'price_lower') %></li>
    <li><%= link_to 'Mayor costo', homes_path(filter: 'price_higher') %></li>
  </section>
</aside>

app/views/partials/_navbar.html.erb
<nav>
  <div class="nav-container">
    <div class="left-nav">
      <div class="logo">
        <%= link_to '<i class="fa-solid fa-paw"></i> <span>PetCare</span>'.html_safe, '/' %>
      </div>
    </div>

    <div class="right-nav">
      <% if user_signed_in? %>
        <%= (link_to 'Hazte anfitrión', edit_user_registration_path) if current_user.guest? %>
      <% end %>
      <ul class="menus" id="menus">
        <li onclick="showGeneralMenu()" class="filter-options" id="filter-options">
          <i class="fa-solid fa-bars"><%= render 'partials/general_options' %></i>
        </li>
        <li onclick="showUserMenu()" class="user-options" id="user-options">
          <i class="fa-regular fa-user"><%= render 'partials/sessions_options' %></i>
        </li>
      </ul>
      <div class="notification-menu" onclick="showNotifications()">
        <i class="fa-solid fa-bell">
        <% if user_signed_in? %>
          <% unless current_user.notifications.unread.size.zero? %>
            <div class="reservation-count">
              <span id="total-notifications"><%= current_user.notifications.unread.size %></span>
            </div>
            <%= render "partials/notifications" %>
          <% end %>
        <% end %>
        </i>
      </div>
    </div>
  </div>
</nav>

app/views/partials/_notifications.html.erb
<section class="notifications-container" id="notifications-container">
  <div class="notifications" id="notifications">
    <% current_user.notifications.unread.each do |notification| %>
      <%= link_to notification.notifiable, id: "#{notification.id}", onclick: 'markAsRead(this);' do %>
        <article class="notification">
          <span><%= notification.text %></span>
        </article>
      <% end %>
    <% end %>
  </div>
  <span id="clear-notifications" onclick="markAsRead(this);">Borrar todos</span>
</section>

app/views/partials/_searcher.html.erb
<%= form_with(
  url: "search_homes",
  local: true, 
  data: {
  controller: :mapsearch,
  action: "google-maps-callback@window->mapsearch#initializeMap"},
  class: "search-home",
  html: {id: "search"}
) do |form| %>

  <div class="location search-section">
    <%= form.label :address, 'Dirección' %>
    <%= form.search_field :address,  class: 'form-control', data: { target: "mapsearch.field", action: "keydown->mapsearch#preventSubmit" } %>
  </div>

  <%= form.hidden_field :latitude, data: { target: "mapsearch.latitude" } %>
  <%= form.hidden_field :longitude, data: { target: "mapsearch.longitude" } %>

  <%= form.hidden_field :ids %>

  <div class="check-in search-section">
    <%= form.label :llegada %>
    <%= form.date_field :llegada , class: 'search-input'%>
  </div>

  <div class="check-in search-section">
    <%= form.label :salida %>
    <%= form.date_field :salida , class: 'search-input'%>
  </div>

  <div class="search">
      <%= button_tag type: 'submit', data: { action: "click->mapsearch#searchNear" }, class: "" do %>
        <div>
          <i class="fa-solid fa-magnifying-glass"></i>
        </div>
      <% end %>
  </div>

<% end %>

app/views/partials/_sessions_options.html.erb
<aside class="session-menu menu" id="session-menu">
  <section class="options-menu">
    <% if !user_signed_in? %>
      <%= link_to "Iniciar sesión", new_user_session_path %>
      <%= link_to "Registrate", new_user_registration_path %>
    <% else %>
      <%= link_to "Mi perfil", profile_users_path %>
      <%= link_to "Cerrar sesión", destroy_user_session_path, data: { turbo_method: :delete } %>
    <% end %>  
  </section>
  <% if current_user %>
    <section class="options-menu">
      <%= link_to "Mis mascotas", pets_path %>
      <%= link_to "Mis reservaciones", reservations_path %>
      <% if current_user.guest? %>
        <%= link_to 'Hazte anfitrión', edit_user_registration_path %>
      <% elsif !current_user.guest? %>
        <%= link_to "Mis alojamientos", my_homes_path %>
      <% end %>
      <% if current_user.role == "admin" %>
        <%= link_to "Admin usuarios", users_path %>
      <% end %>
    </section>
  <% end %>
</aside>