config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reservations, except: [:destroy]
  resources :reviews, only: [:show, :new, :create]
  resources :homes
  resources :pets
  resources :users, only: [:show] do
    collection do 
      get :profile
    end
  end

  get '/homes/:id/reviews' => 'reviews#index', as: 'homes_reviews'
  get '/homes/:id/delete' => 'homes#destroy', as: 'homes_delete'
  get '/pets/:id/delete' => 'pets#destroy', as: 'pets_delete'
  get 'users/index'
  post 'notifications/:id/mark_as_read' => 'notifications#mark_as_read'
  post 'notifications/mark_as_read' => 'notifications#mark_as_read'


  root 'pages#home'

  match '/users',   to: 'users#index', via: 'get'
  put '/users/:id', action: :verify, controller: 'users'
  post '/search_homes' => 'homes#search'
  get '/search_homes' => 'homes#index'
  get '/my_homes' => 'homes#my_homes', as: 'my_homes'

  get '/homes/search_homes', action: :index, controller: 'homes'

  post '/reservations/new', to: 'reservations#new'
end

app/models/reservation.rb
# frozen_string_literal: true

class Reservation < ApplicationRecord
  belongs_to :guest, class_name: 'User'
  belongs_to :host, class_name: 'User'
  belongs_to :home
  has_one :review

  validates :check_in, :check_out, :pets_number, presence: true
  validate :same_user?
  validate :valid_dates?
  validate :available?
  validate :set_amount
  after_create :create_notifications
  after_save :create_review_notification

  scope :valid_update, lambda { |check_out, check_in, id, home_id|
                         where('check_in <= ? and check_out >= ? and id <> ? and home_id = ? and status <> 2', check_out, check_in, id, home_id)
                       }
  scope :valid_create, lambda { |check_out, check_in, home_id|
                         where('check_in <= ? and check_out >= ? and home_id = ? and status <> 2', check_out, check_in, home_id)
                       }
  scope :guest_status, lambda { |stat, guest| where('status = ? and guest_id = ?', stat, guest).order(created_at: :desc) }
  scope :host_status, lambda { |stat, host| where('status = ? and host_id = ? ', stat, host).order(created_at: :desc) }
  scope :reserved_dates, -> { where('status <> 2') }

  enum status: { pending: 0, aproved: 1, canceled: 2, finished: 3 }

  def available?
    taken = if id
              Reservation.valid_update(check_out, check_in, id, home_id)
            else
              Reservation.valid_create(check_out, check_in, home_id)
            end
    errors.add('Hay una reservación en la fecha seleccionada') unless taken.size.zero?
  end

  def same_user?
    errors.add('No puedes reservar tu propia casa') if guest_id == host_id
  end

  def valid_dates?
    correct_date = check_in < check_out
    errors.add('Tu fecha de salida no puede ser menor a la fecha de entrada') unless correct_date
  end

  def set_amount
    self.amount = (check_out - check_in).to_i * home.price
  end

  def self.update_pending_reservation
    reservations = Reservation.where('status = ? and check_in < ?', 0, Date.today)
    reservations.each { |reservation| reservation.update(status: 2) }
  end

  def self.update_approved_reservation
    reservations = Reservation.where('status = ? and check_out < ?', 1, Date.today)
    reservations.each { |reservation| reservation.update(status: 3) }
  end

  def start_time
    self.check_in
  end

  def end_time
    self.check_out
  end
  
  def create_notifications
    msg = "#{guest.name} necesita un lugar para su mascota del #{check_in.strftime('%d/%m/%Y')} al #{check_out.strftime('%d/%m/%Y')}"
    Notification.create(recipient: host, notifiable: self, text: msg)
  end

  def create_review_notification
    if status == 'finished'
      msg = "Realice un comentario sobre su estadía en '#{home.title}'"
      Notification.create(recipient: guest, notifiable: self, text: msg)
    end
  end

  def translate_status
    options = { pending: 'Pendiente', aproved: 'Aprobado', canceled: 'Cancelado', finished: 'Finalizado' }
    options[self.status.to_sym]
  end
end

app/controllers/reservations_controller.rb
# frozen_string_literal: true

class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[show edit update]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /reservations or /reservations.json
  def index
    @guest_reservations = Reservation.where(guest_id: current_user).order(created_at: :desc)
    @host_reservations = Reservation.where(host_id: current_user).order(created_at: :desc)
    if params.key?(:status)
      @guest_reservations = Reservation.guest_status(params[:status], current_user)
      @host_reservations = Reservation.host_status(params[:status], current_user)
    end
  end

  # GET /reservations/1 or /reservations/1.json
  def show; end

  # GET /reservations/new
  def new
    @home = Home.find_by(id: params[:home])
    @reservation = Reservation.new
    @reservation.check_in = params[:check_in]
    @reservation.check_out = params[:check_out]
    redirect_to homes_path unless params.key?(:home)
  end

  # GET /reservations/1/edit
  def edit
    @home = @reservation.home
  end

  # POST /reservations or /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)
    
    @home = Home.find_by(id: @reservation.home_id)
    @reservation.guest = current_user
    @reservation.host = @home.user
    respond_to do |format|
      if @reservation.save
        format.html { redirect_to reservation_url(@reservation), notice: 'Su reservación fue realizada correctamente' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    @reservation.status = 'pending'
    @home = Home.find_by(id: @reservation.home_id)
    respond_to do |format|
      if @reservation.update(reservation_params)
        create_notifications unless @reservation.finished?
        format.html { redirect_to reservation_url(@reservation), notice: 'Los datos de su reservación se actualizaron correctamente' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def reservation_params
    params.require(:reservation).permit(:home_id, :check_in, :check_out, :pets_number, :amount, :status)
  end

  def create_notifications
    if current_user == @reservation.guest
      msg = "#{current_user.name} realizo un cambio en su reservación"
      Notification.create(recipient: @reservation.host, notifiable: @reservation, text: msg)
    else
      msg = "#{current_user.name} actualizo el estado de la reservación"
      Notification.create(recipient: @reservation.guest, notifiable: @reservation, text: msg)
    end
  end
end

app/views/reservations/_form.html.erb
<%= form_with(model: reservation, class: 'reservation-form') do |form| %>
  <% if reservation.errors.any? %>
    <div class="invalid-form">
    <p>Ha ocurrido un error:</p>
      <aside>
        <% reservation.errors.each do |error| %>
          <p><%= error.attribute %></p>
        <% end %>
      </aside>
    </div>
  <% end %>

  <% unless action_name == 'edit' %>
    <div class="hidden">
      <%= form.hidden_field :home_id, value: @home.id %>
    </div>
  <% end %>
  
  <div class="field">
    <%= form.label :check_in, style: "display: block" %>
    <%= form.date_field :check_in, min: Date.today, required: true, onchange: 'totalAmount()' %>
  </div>

  <div class="field">
    <%= form.label :check_out, style: "display: block" %>
    <%= form.date_field :check_out, min: (Date.today + 1.days), required: true, onchange: 'totalAmount()' %>
  </div>

  <div class="field">
    <%= form.label :pets_number, style: "display: block" %>
    <%= form.select :pets_number, (1..current_user.pets.size), required: true %>
  </div>

  <div class="confirm">
    <div>
      <h3>Total:</h3>
      <p id="price" hidden><%= @home.price %></p>
      <p id="amount">$0</p>
    </div>

    <div class="actions">
      <%= form.submit 'Confirmar reservación' %>
    </div>
  </div>
<% end %>

app/views/reservations/_reservation.html.erb
<article class="reservation <%= reservation.status %>">
  <div class="reservation-detail">
    <h1><%= reservation.home.title %></h1>
    <section class="reservation-info">
      <%= link_to reservation.home, class: 'home-link' do %>
        <%= image_tag reservation.home.photos[0].variant(resize_to_limit: [500, 500]) %>
      <% end %>
      <div class="reservation-home-info">
        <p><%= reservation.home.address %></p>
        <%= link_to user_path(reservation.home), class: 'user-link' do %>
          <%= reservation.home.user.name %>
        <% end %>
        <p class="phone">Cel: <%= reservation.home.user.phone %></p>
      </div>
    </section>
    <section class="reservation-date">
      <p>
        Se solicitó una reservación del 
        <strong><%= reservation.check_in.strftime('%d/%m/%Y') %></strong> al 
        <strong><%= reservation.check_out.strftime('%d/%m/%Y') %></strong>
      </p>
    </section>
  </div>
  <div class="reservation-guest">
    <h1>Reservación solicitada por:</h1>
    <div>
      <p><strong>Huesped:</strong> <%= link_to reservation.guest.name, user_path(reservation.guest) %></p>
      <p><strong>Mascotas a cuidar:</strong> <%= reservation.pets_number %></p>
      <p><strong>Status:</strong> <%= reservation.translate_status %></p>
    </div>
    <p>Total: <strong>$<%= reservation.amount %></strong></p>
  </div>
  <% if action_name == 'show' %>
    <% if @reservation.pending? && @reservation.host == current_user %>
      <div class="status-buttons">
        <%= button_to "Rechazar reservación", reservation_path(@reservation, reservation: { status: 'canceled' }), method: :put, class: 'cancel-button' %>
        <%= button_to "Aceptar reservación", reservation_path(@reservation, reservation: { status: 'aproved' }), method: :put, class: 'approve-button' %>
      </div>
    <% else %>
      <% unless @reservation.canceled? || @reservation.finished? %>  
        <div class="status-buttons">
          <%= button_to "Cancelar reservación", reservation_path(@reservation, reservation: { status: 'canceled' }), method: :put, class: 'cancel-button' %>
          <% if @reservation.host == current_user && @reservation.check_in <= Date.today %>
            <%= button_to "Finalizar reservación", reservation_path(@reservation, reservation: { status: 'finished' }), method: :put, class: 'finish-button' %>
          <% end %>
        </div>
      <% end %>
    <% end %>    
  <% end %>
  <% if left_review?(reservation.home_id, reservation) %>
    <%= link_to new_review_path(reservation: reservation), class: 'review-link' do %>
      <span>Deja un comentario</span><i class="fa-solid fa-comment-dots"></i>
    <% end %>
  <% end %>
</article>

app/views/reservations/_reservation_index.html.erb
<article class="reservation <%= reservation.status %>">
  <div class="reservation-detail">
    <h1><%= reservation.home.title %></h1>
    <section class="reservation-info info-index">
      <div>
        <strong><p>Dirección:</p></strong>
        <p><%= reservation.home.address %></p>
        <strong><p>Ofrecido:</p></strong>
        <p><%= reservation.home.user.name %></p>
        <p class="phone">Cel: <%= reservation.home.user.phone %></p>
      </div>
    </section>
    <section class="reservation-date">
      <p>
        Se solicito una reservación del 
        <strong><%= reservation.check_in.strftime('%d/%m/%Y') %></strong> al 
        <strong><%= reservation.check_out.strftime('%d/%m/%Y') %></strong>
      </p>
    </section>
  </div>
  <div class="reservation-guest">
    <h1>Reservación solicitada por:</h1>
    <div>
      <p><strong>Huesped:</strong> <%= reservation.guest.name %></p>
      <p><strong>Mascotas a cuidar:</strong> <%= reservation.pets_number %></p>
      <p><strong>Estatus:</strong> <%= reservation.translate_status %></p>
    </div>
    <p>Total: <strong>$<%= reservation.amount %></strong></p>
  </div>
  <% if left_review?(reservation.home_id, reservation) %>
    <i class="fa-solid fa-comment-dots left-review"></i>
  <% end %>
</article>

app/views/reservations/edit.html.erb
<main class="reservation-main">
  <h1>¿Necesitas algun cambio?</h1>

  <section class="reservation-info">
    <%= image_tag @home.photos[0].variant(resize_to_limit: [500, 500]) %>
    <div>
      <h2><%= @home.title %></h2>
      <h3>Dirección:</h3>
      <p><%= @home.address %></p>
      <h3>Ofrecido:</h3>
      <%= link_to @home.user.name, user_path(@home.user)%>
    </div>
  </section>

  <%= render "form", reservation: @reservation %>
</main>

<div>
  <%= link_to "Show this reservation", @reservation %> |
  <%= link_to "Back to reservations", reservations_path %>
</div>

<%= javascript_include_tag 'reservation' %>

app/views/reservations/index.html.erb
<main class="reservation-main reservation-index">
  <h1>Reservaciones</h1>
  <div class="reservation-filter">
    <% if @host_reservations.size.zero? and @guest_reservations.size.zero? %>
      <div>
        <section class="filter-reservation">
          <%= link_to 'Todas', reservations_path %>
          <%= link_to 'Pendientes', reservations_path(status: 0) %>
          <%= link_to 'Canceladas', reservations_path(status: 2) %>
          <%= link_to 'Aprobadas', reservations_path(status: 1) %>
          <%= link_to 'Finalizadas', reservations_path(status: 3) %>
        </section>
      </div>
      <p>No ha realizado ninguna reservación o no tiene ninguna del tipo seleccionado</p>
    <% else %>
    <div>
      <section class="filter-reservation">
        <%= link_to 'Todas', reservations_path %>
        <%= link_to 'Pendientes', reservations_path(status: 0) %>
        <%= link_to 'Canceladas', reservations_path(status: 2) %>
        <%= link_to 'Aprobadas', reservations_path(status: 1) %>
        <%= link_to 'Finalizadas', reservations_path(status: 3) %>
      </section>
    </div>
    <section>
      <% unless @guest_reservations.size.zero? %>
        <h3>Hechas</h3>
        <div class="revervation-container">
          <% @guest_reservations.each do |reservation| %>
            <div class="guest-reservation">
              <%= link_to reservation_path(reservation) do %>
                  <%= render "reservation_index", reservation: reservation %>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
      <% unless @host_reservations.size.zero? %>
        <h3>Solicitadas</h3>
        <div class="revervation-container">
          <% @host_reservations.each do |reservation| %>
            <div class="host-reservation">
              <%= link_to reservation_path(reservation) do %>
                  <%= render "reservation_index", reservation: reservation %>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </section>
  <% end %>
</main>

app/views/reservations/new.html.erb
<h1>Realiza tu reservación</h1>
<main class="reservation-main reservation-new">
  <div>
    <h2><%= @home.title %></h2>
  </div>
  <div class="info-reservation-desktop">
    <section class="reservation-info">
      <%= image_tag @home.photos[0].variant(resize_to_limit: [500, 500]) %>
    </section>
    <%= render "form", reservation: @reservation %>
  </div>
</main>

<div>
  <%= link_to '<i class="fa-solid fa-arrow-rotate-left"></i>'.html_safe, home_path(@home) %>
</div>
<%= javascript_include_tag 'reservation' %>

app/views/reservations/show.html.erb
<main class="reservation-show">
  <%= render @reservation %>

  <div class="links">
    <% if @reservation.guest == current_user && !(@reservation.finished? || @reservation.canceled?) %>
      <%= link_to '<i class="fa-solid fa-pen-to-square"></i>'.html_safe, edit_reservation_path(@reservation) %>
    <% end %> 
    <%= link_to '<i class="fa-solid fa-arrow-rotate-left"></i>'.html_safe, reservations_path %>
  </div>
</main>