config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reservations, except: [:destroy]
  resources :reviews, only: [:show, :new, :create]
  resources :homes
  resources :pets
  resources :users, only: [:show] do
    collection do 
      get :profile
    end
  end

  get '/homes/:id/reviews' => 'reviews#index', as: 'homes_reviews'
  get '/homes/:id/delete' => 'homes#destroy', as: 'homes_delete'
  get '/pets/:id/delete' => 'pets#destroy', as: 'pets_delete'
  get 'users/index'
  post 'notifications/:id/mark_as_read' => 'notifications#mark_as_read'
  post 'notifications/mark_as_read' => 'notifications#mark_as_read'


  root 'pages#home'

  match '/users',   to: 'users#index', via: 'get'
  put '/users/:id', action: :verify, controller: 'users'
  post '/search_homes' => 'homes#search'
  get '/search_homes' => 'homes#index'
  get '/my_homes' => 'homes#my_homes', as: 'my_homes'

  get '/homes/search_homes', action: :index, controller: 'homes'

  post '/reservations/new', to: 'reservations#new'
end

app/models/home.rb
class Home < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many_attached :photos

  validates :title, :address, :description, :price, presence: true
  validate :verified_user?

  scope :filter_by_price_lower, -> { order :price }
  scope :filter_by_price_higher, -> { order price: :desc }
  scope :filter_by_score, -> { order score: :desc }
  scope :filter_by_date, -> { order created_at: :desc }

  def verified_user?
    errors.add('Debes estar verificado para registrar casas') unless user.verified?
  end

  def self.search_filter(filtering_param)
    results = self.where(nil)
    results = results.public_send("filter_by_#{filtering_param}")
    results
  end

  def self.update_score(home)
    reviews = Review.where(home_id: home.id)
    score = 0
    reviews.each { |review| score += review.score }
    home.update(score: (score/reviews.size))
  end
end

app/controllers/homes_controller.rb
# frozen_string_literal: true

class HomesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show search]
  load_and_authorize_resource
  skip_before_action :verify_authenticity_token,  only: [:search, :index]

  # GET /homes or /homes.json
  def index
    @ids = params[:homes_ids] if params.key?(:homes_ids)
    @homes = params.key?(:homes_ids) ? Home.where(id: @ids) : Home.all
    @homes = @homes.search_filter(params[:filter]) if params.key?(:filter)
  end

  # GET /homes/1 or /homes/1.json
  def show
    @reviews = Review.where(home: @home).limit(4)
    @meetings = @home.reservations.reserved_dates
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
    delete_attachment(params[:photo_id]) if params.key?(:photo_id)
  end

  # POST /homes or /homes.json
  def create
    @home = Home.new(home_params)
    @home.user = current_user

    respond_to do |format|
      if @home.save
        format.html { redirect_to home_url(@home), notice: 'Su casa fue registrada correctamente' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1 or /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to home_url(@home), notice: 'Los datos de su casa se actualizaron correctamente' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1 or /homes/1.json
  def destroy
    @home.destroy

    respond_to do |format|
      format.html { redirect_to my_homes_path, notice: 'El registro de su casa fue eliminado correctamente' }
    end
  end

  def delete_attachment(photo_id)
    attachment = ActiveStorage::Attachment.find(photo_id)
    attachment.purge
    redirect_to edit_home_url(@home)
  end

  def search
    @ids = params[:ids].split(',')
    if params[:llegada] != "" && params[:salida] != "" 
      @ids = @ids.reject { |id| (Reservation.valid_create(params[:salida], params[:llegada], id).size > 0) }
    end
    @homes = Home.where(id: @ids)
    render action: "index", locals: { homes: @homes, ids: @ids }
  end

  def my_homes
    @homes = Home.where(user: current_user)
    @homes = @homes.search_filter(params[:filter]) if params.key?(:filter)
  end

  private

  # Only allow a list of trusted parameters through.
  def home_params
    params.require(:home).permit(:title, :address, :latitude, :longitude, :description, :price, :score, :user_id, photos: [])
  end
end

app/views/homes/_form.html.erb
<%= form_with(model: home , local: true, data: { controller: :maps, action: "google-maps-callback@window->maps#initializeMap" }) do |form| %>
  <% if home.errors.any? %>
    <div class="invalid-form">
      <p>Ha ocurrido un error: </p>
      <aside>
        <% home.errors.each do |error| %>
          <p><%= error.attribute %></p>
        <% end %>
      </aside>
    </div>
  <% end %>

  <div class="new-desktop">
    <div class="new-home-cont">
      <div class="new-home-photo">
        <div class="file-field">
          <%= form.label :photos do %>
            <span><strong>Subir fotos:</strong></span>
            <% if action_name == 'new' %>
              <%= form.file_field :photos, multiple: true, onchange: 'loadFiles(event)', class: 'input-file', required: true %>
            <% else %>
              <%= form.file_field :photos, multiple: true, onchange: 'loadFiles(event)', class: 'input-file' %>
            <% end %>
            <div class="upload photos-field" id="upload">
              <span id="add">+</span>
            </div>
          <% end %>
        </div>
      </div>
      <div class="new-home-form">
        <% if action_name == 'new' %>
          <h1>Registra una nueva casa</h1>
        <% else %>
          <h1>Actualiza la información de tu casa</h1>
        <% end %>
        <div class="field">
          <%= form.label :title, 'Título', style: "display: block" %>
          <%= form.text_field :title, placeholder: 'Escribe un título para tu casa' %>
        </div>

      <div class="field">
        <%= form.label :address, 'Dirección' %>
        <%= form.text_area :address, placeholder: 'Ingresa tu dirección' %>
      </div>

        <div class="field">
          <%= form.hidden_field :latitude, class: 'form-control', data: { target: "maps.latitude" } %>
        </div>

        <div class="field">
          <%= form.hidden_field :longitude, class: 'form-control', data: { target: "maps.longitude" } %>
        </div>

        <div class="field">
          <%= form.label :description, 'Descripción',  style: "display: block" %>
          <%= form.text_area :description, placeholder: 'Escribe una breve descripción de tu casa' %>
        </div>

        <div class="field">
          <%= form.label :price, 'Costo', style: "display: block" %>
          <%= form.text_field :price, placeholder: 'Costo por día' %>
        </div> 
        
      </div>
    </div>

    <strong>Busca tu casa en el mapa</strong>
    <input id="pac-input" class="controls form-control" type="search" placeholder="Busca tu casa" data-target="maps.field" data-action="keydown->maps#preventSubmit"/>
    <%= content_tag :div, nil, data: { target: "maps.map" }, class: 'map', id: 'map' %>

    <% if action_name == 'edit' %>
      <span><strong>Fotos actuales:</strong></span>
      <div class="field photos-field photos-delete">
        <% home.photos.each do |photo| %>
          <%= link_to edit_home_path(home, photo_id: photo), class: 'photo' do %>
            <%= image_tag(photo) %>
            <div class="trash-icon">
              <i class="fa-solid fa-trash-can"></i>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>

    <div class="button-back">
      <div class="actions">
        <%= form.submit 'Guardar', class: "button" %>
      </div>
    </div>
  </div>
<% end %>
<div id="icon-back links">
  <a href= <%= homes_path %>><i class="fa-solid fa-arrow-rotate-left"></i></a>
</div>

app/views/homes/_home.html.erb
<div id="<%= dom_id home %>">
  <p>
    <strong>Title:</strong>
    <%= home.title %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= home.address %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= home.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= home.price %>
  </p>

  <p>
    <strong>Score:</strong>
    <%= home.score %>
  </p>

  <p>
    <strong>User:</strong>
    <%= home.user_id %>
  </p>

  <p>
    <strong>Home Photos:</strong>
    <% home.photos.each do |photo| %>
      <%= image_tag photo.variant(resize_to_limit: [100, 100]) %>
    <% end %>
  </p>

  <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=16&size=400x300&markers=color:red|label:P|#{home.latitude},#{home.longitude}&center=#{home.latitude},#{home.longitude}&key=#{ENV['MAPS_API_KEY']}" %>
  
</div>

app/views/homes/_home_card.html.erb
<div class="home-card" id="<%= dom_id home %>">
  <figure>
    <%= image_tag home.photos[0].variant(resize_to_limit: [500, 500]) %>
  </figure>
  
  <div class="home-info">
    <p>
      <%= home.title %>
    </p>

    <p>
      <i class="fa-solid fa-star"></i>
      <%= home.score %>
    </p>

    <p>
      <%= home.address %>
    </p>

    <p>
      $<%= home.price %> MXN
    </p>

  </div>

</div>

app/views/homes/_homes.html.erb
<main class="homes-main">
  <%= render 'partials/searcher' %>

  <nav class="filter-nav">
    <ul>
      <li><%= link_to 'Más recientes', homes_path(filter: 'date', homes_ids: ids) %></li>
      <li><%= link_to 'Mejor reputación', homes_path(filter: 'score', homes_ids: ids) %></li>
      <li><%= link_to 'Menor costo', homes_path(filter: 'price_lower', homes_ids: ids) %></li>
      <li><%= link_to 'Mayor costo', homes_path(filter: 'price_higher', homes_ids: ids) %></li>
    </ul>
  </nav>

  <div class="homes" id="homes">
    <% homes.each do |home| %>
      <%= link_to home, class: 'home-card-container' do %>
        <%= render 'home_card', home: home %>
      <% end %>
    <% end %>
  </div>
</main>

app/views/homes/edit.html.erb
<%= render "form", home: @home %>

app/views/homes/index.html.erb
<main class="homes-main">
  <%= render 'partials/searcher' %>

  <nav class="filter-nav">
    <ul>
      <li><%= link_to 'Más recientes', homes_path(filter: 'date', homes_ids: @ids) %></li>
      <li><%= link_to 'Mejor reputación', homes_path(filter: 'score', homes_ids: @ids) %></li>
      <li><%= link_to 'Menor costo', homes_path(filter: 'price_lower', homes_ids: @ids) %></li>
      <li><%= link_to 'Mayor costo', homes_path(filter: 'price_higher', homes_ids: @ids) %></li>
    </ul>
  </nav>

  <div class="homes" id="homes">
    <% @homes.each do |home| %>
      <%= link_to home, class: 'home-card-container' do %>
        <%= render 'home_card', home: home %>
      <% end %>
    <% end %>
  </div>
</main>

app/views/homes/my_homes.html.erb
<main class="homes-main">
  <%= render 'partials/searcher' %>

  <nav class="filter-nav">
    <ul>
      <li><%= link_to 'Más recientes', my_homes_path(filter: 'date') %></li>
      <li><%= link_to 'Mejor reputación', my_homes_path(filter: 'score') %></li>
      <li><%= link_to 'Menor costo', my_homes_path(filter: 'price_lower') %></li>
      <li><%= link_to 'Mayor costo', my_homes_path(filter: 'price_higher') %></li>
    </ul>
  </nav>

  <div class="homes" id="homes">
    <% @homes.each do |home| %>
      <%= link_to home, class: 'home-card-container' do %>
        <%= render 'home_card', home: home %>
      <% end %>
    <% end %>
    <%= link_to new_home_path, class: 'home-card add-model' do %>
      <span>+</span>
    <% end %>
  </div>
</main>

app/views/homes/new.html.erb
<h1 id="first">New home</h1>
<%= render "form", home: @home %>

app/views/homes/show.html.erb
<div class="show-desktop">
  <h2><%= @home.title %></h2>
  <section class="principal-info">
    <div class="first-section">
      <div class="img-photo">
        <div class="button-img">
          <button class="back">&#60</button>
          <button class="forward">&#62</button>
        </div>
        <%= image_tag @home.photos[0].variant(resize_to_limit: [500, 500]), class: "img-main active" %>
        <aside class="photos-selection">
          <% @home.photos.each do |photo| %>
            <%= image_tag photo, class: "photo-secundary" %>
          <% end %>
        </aside>
      </div>
    </div>
    <div class = "reputation" >
      <div class="score">
        <i class="fa-solid fa-star"></i>
        <span><%= @home.score %></span><br>
        <p>(<%= Review.total_reviews(@home.id) %> comentarios)</p>
      </div>
      <%= link_to user_path(@home.user), class: 'user-link' do %>
        <%= image_tag@home.user.profile_photo.variant(resize_to_limit: [100, 100]) %>
        <%= @home.user.name %>
      <% end %>
    </div>
    <p><strong>Disponibilidad</strong></p>
    <%= render 'partials/calendar', meetings: @meetings %>
  </section>
  <div class="content-show">
    <h3 class="show-house-text"><%= @home.description%></h3>
    <div class="address">
      <p><strong>Ubicado en:</strong> <%= @home.address %></p>
      <a href="https://www.google.com/maps/search/?api=1&query=<%= @home.latitude%>%2C<%= @home.longitude%>" target=_blank><i class="fa-solid fa-location-dot"></i> Ver en Google Maps</a>
    </div>
    <div class="home-reservation">
      <%= form_with url: new_reservation_url(home: @home), data: { turbo: "false" }, method: 'post'  do |f| %>
        <div class = "reservation">
          <h3>Agenda tu reservación</h2>
          <div class="reservation-preview">
            <div class="days">
              <div>
                <p>Llegada</p>
                <span><%= f.date_field :check_in, min: Date.today, value: Date.today  %></span>
              </div>
              <div>
                <p>Salida</p>
                <span><%= f.date_field :check_out, min: (Date.today + 1.days), value: (Date.today + 1.days) %></span>
              </div>
            </div>
            <div class ="pets">
              <%= f.label "Mascotas", style: "display: block" %>
              <% if user_signed_in? %>
                <%= f.select :pets_number, (1..current_user.pets.size) %>
              <% else %>
                <%= f.select :pets_number, [1,2,3,4] %>
              <% end %>
              
            </div>
          </div>
          <%= f.submit "Reservar", class: 'btn-reservation'%>
        </div>
      <% end %>
    </div>
    <div class="opinions">
      <h3>Opiniones</h2>
        <% if Review.total_reviews(@home.id) <= 0 %>
          <p>Esta casa no tiene comentarios</p>
        <% else %>
          <div class="reviews">
            <% @reviews.each do |review| %>
              <div class="opinion" id=<%= dom_id review %>>
                  <%= link_to review do %>
                    <%= render review %>
                  <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
      <div class="plus">
        <%= link_to 'Mostrar más', homes_reviews_path %>
      </div>
    </div>
  </div>
  <script> photos(); photosMobile(); </script>
</div>
<div class="links">
  <% if current_user == @home.user %>
    <a href= <%= edit_home_path(@home) %>><i class="fa-solid fa-pen-to-square"></i></a>
  <% end %>
  <a href= <%= homes_path %>><i class="fa-solid fa-arrow-rotate-left"></i></a>
  <% if current_user == @home.user %>
    <%= link_to '<i class="fa-solid fa-trash-can"></i>'.html_safe, homes_delete_path(@home) %>
  <% end %>
</div>